services:
  postgres1:
    image: postgres:alpine
    container_name: postgres1
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: mydb
    ports:
      - "15432:5432"
  postgres2:
    image: postgres:alpine
    container_name: postgres2
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: testdb
    ports:
      - "25432:5432"
