version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./1_init.sql:/docker-entrypoint-initdb.d/1_init.sql
